server:
  port: 8777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kusoul?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    check-template-location: false
  security:
    user:
      roles:
  redis:
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis连接时间
    timeout: 5000
    # Redis服务器连接端口
    port: 6379
    password: redis
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 0
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.example.kusoul.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  configuration:
    map-underscore-to-camel-case=false:

