server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kusoul?useUnicode=true&characterEncoding=utf-8
    username: root
    data-password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    check-template-location: false
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.example.kusoul.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


