server:
  port: 8777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kusoul?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    check-template-location: false
  security:
    user:
      roles:
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.example.kusoul.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  configuration:
    map-underscore-to-camel-case=false:


